@startuml
'https://plantuml.com/class-diagram

class Person {
== Variables ==
int age;
String name;
String title;

== Getters ==
getAge();
getName();

== Setters ==
setAge();
setName();
}

class User {
  .. Simple Getter ..
  + getName()
  + getAddress()
  .. Some setter ..
  + setName()
  __ private data __
  -int age
  -- encrypted --
  String password
}

@enduml